ICOSCoreNew/Models/BADM/BaseController.cs
using ICOSCoreNew.DB;
using ICOSCoreNew.Models.Utils;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

namespace ICOSCoreNew.Models.BADM
{
    [Serializable]
    public class OperationResponse
    {
        public int code { get; set; }
        public string message { get; set; }
    }


    public class BaseController : Controller
    {
        protected const string OPERATION_UPDATE = "Update";
        protected const string OPERATION_ADD = "Create";
        protected const string OPERATION_DELETE = "Delete";
        public JsonResult Create<M, A, U>(U ui, int siteid, string validationmembername, int groupid)
                                    where M : class, new()
                                    where A : class, new()
                                    where U : class
        {
            OperationResponse res = new OperationResponse { code = 0, message = "Add complete" };
            if (this.ModelState.IsValid)
            {
                try
                {
                    var model = Activator.CreateInstance<M>();
                    var adapter = Activator.CreateInstance<A>();
                    var servervalidator = Activator.CreateInstance(typeof(ServerValidator));
                    //
                    MethodInfo mi = servervalidator.GetType().GetMethod(validationmembername);
                    string validateReturn = "Ok";
                    if (null != mi) validateReturn = (string)mi.Invoke(servervalidator, new object[] { ui });
                    if (validateReturn.Length == 0)
                    {
                        model.GetType().GetMethod("Add").Invoke(model, new object[]{
                    adapter.GetType().GetMethod("Adapt",new Type[]{typeof(U)}).Invoke(adapter,new object[]{ui})
                    ,AccountDA.CurrentUserID
                    ,siteid
                    ,groupid
                  });
                    }
                    else
                    {
                        res.code = 200;
                        res.message = validateReturn;
                    }
                }
                catch (Exception ex)
                {
                    res.code = 200;
                    res.message = "Database error";
                }
                return Json(res);
            }
            else
            {
                res.code = 100;
                res.message = "Model is not valid";
            }
            return Json(res);
        }
        public JsonResult getData<M, A, F, U>(F filter) where M : class, new()
                                                    where A : class, new()
                                                    where F : class, new()
                                                    where U : class, new()
        {
            try
            {
                string site = "";//System.Web.HttpContext.Current.Session["PiSite"].ToString();
                if (string.IsNullOrEmpty(site)) site = "-1";
                filter.GetType().GetProperty("SITE").SetValue(filter, site);
            }
            catch (Exception ex)
            {
                var err = ex.ToString();
                // TODO: AC - what to do ??
            }
            var model = Activator.CreateInstance<M>();
            var adapter = Activator.CreateInstance<A>();
            var resList = adapter.GetType().GetMethod("Adapt", new Type[] { typeof(List<M>) }).Invoke(adapter, new object[] { model.GetType().GetMethod("GetData", BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly).Invoke(model, new object[] { filter }) }) as List<U>;
            // filters
            List<string> xparm = new List<string>();
            Type myType = filter.GetType();
            IList<PropertyInfo> props = new List<PropertyInfo>(myType.GetProperties());
            int contaparms = 0;
            string xdynque = @"";
            foreach (PropertyInfo prop in props)
            {
                if (prop.Name != "SITE")
                {
                    object propValue = prop.GetValue(filter, null);
                    if (propValue != null)
                    {
                        // add to filer string
                        //xdynque = prop.Name.Replace("_DESCRIPTION", "") + @".Contains(@" + contaparms.ToString() + ") AND ";
                        xdynque = xdynque + prop.Name + @".Contains(@" + contaparms.ToString() + ") AND ";
                        // 
                        xparm.Add(propValue.ToString());

                        contaparms++;
                    }
                }

                // Do something with propValue
            }


            if (xparm.Count > 0)
            {
                xdynque = xdynque.Substring(0, xdynque.Length - 5);
                //resList=resList.Where(xdynque)
                //resList = resList.Where(xdynque, xparm.ToArray()).ToList();
            }
            return Json(resList);
        }
        public JsonResult Edit<M, A, U>(U ui, string validationmembername, int groupid) where M : class where A : class, new() where U : class
        {
            OperationResponse res = new OperationResponse { code = 0, message = "" };
            if (ModelState.IsValid)
            {
                try
                {
                    int xsite = 0;
                    // TODO: DIEGO_____ check site ( refactor to function..)
                   /* if (System.Web.HttpContext.Current.Session["PiSite"] != null)
                    {
                        int.TryParse(System.Web.HttpContext.Current.Session["PiSite"].ToString(), out xsite);
                    }*/
                    if (xsite > 0)
                    {
                        var adapter = Activator.CreateInstance<A>();
                        var model = Activator.CreateInstance<M>();
                        model = adapter.GetType().GetMethod("Adapt", new Type[] { typeof(U) }).Invoke(adapter, new object[] { ui }) as M;
                        var servervalidator = Activator.CreateInstance(typeof(ServerValidator));
                        //
                        MethodInfo mi = servervalidator.GetType().GetMethod(validationmembername);
                        string validateReturn = "Ok";
                        if (null != mi) validateReturn = (string)mi.Invoke(servervalidator, new object[] { model });
                        if (validateReturn.Length == 0)
                        {
                            model.GetType().GetMethod(OPERATION_UPDATE).Invoke(model, new object[]{
                    adapter.GetType().GetMethod("Adapt",new Type[]{typeof(U)}).Invoke(adapter,new object[]{ui})
                    ,AccountDA.CurrentUserID
                    ,xsite
                    ,groupid
                  });
                        }
                        else
                        {
                            res.code = 200;
                            res.message = validateReturn;
                        }
                    }
                    else
                    {
                        res.code = 300;
                        res.message = "Please select a valid site";
                    }
                }
                catch (Exception ex)
                {
                    res.code = 500;
                    res.message = "Unable to edit values";
                }
            }
            else
            {
                res.code = 50;
                res.message = "Please check invalid fields";
            }
            return Json(res);
        }
        public JsonResult Delete<M, A, U>(U ui) where M : class, new() where A : class, new() where U : class
        {
            OperationResponse res = new OperationResponse { code = 0, message = "Record deleted" };
            try
            {
                var model = Activator.CreateInstance<M>();
                var adapter = Activator.CreateInstance<A>();
                model.GetType().GetMethod(OPERATION_DELETE).Invoke(model, new object[]{
               adapter.GetType().GetMethod("Adapt",new Type[]{typeof(U)}).Invoke(adapter,new object[]{ui})
              ,AccountDA.CurrentUserID
            });
            }
            catch (Exception ex)
            {
                res.code = ex.HResult;
                res.message = "Unable to delete item.Please contact help desk.";
            }
            return Json(res);
        }
    }
}

ICOSCoreNew/Models/BADM/LocationGroup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ICOSCoreNew.Models.BADM
{
    public class LocationGroup
    {
        public const int GROUP_ID = 3;
       // newIcos.DB.DB db;
        public string LOCATION_LAT { get; set; }
        public string LOCATION_LONG { get; set; }
        public string LOCATION_ELEV { get; set; }
        public string LOCATION_DATE { get; set; }
        public string LOCATION_COMMENT { get; set; }
    }
}

ICOSCoreNew/Models/BADM/LocationGroupAdapter.cs
using ICOSCoreNew.Models.DTO;
using ICOSCoreNew.Models.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace ICOSCoreNew.Models.BADM
{
    public class LocationGroupAdapter : IVariableAdapter<LocationGroup>
    {
        private readonly ICOSEntities dbContext;

        public LocationGroupAdapter(ICOSEntities _dbc)
        {
            this.dbContext = _dbc;
        }

        public LocationGroup GetVariableFromDataStorage(int siteId, int groupId)
        {
            SqlParameter sid = new SqlParameter("@siteId", siteId);
            SqlParameter grid = new SqlParameter("@grId", groupId);
            object[] pars = {sid, grid };
            //var result = dbContext.DataStorages.FromSql("SelectDataGeneralUI", parameters: new[] { "@siteId", 70,  }).SingleOrDefault();
            var result = dbContext.DataStorages.FromSql("EXEC SelectDataGeneralUI @siteId, @grId", sid, grid);
            DataStorage d = (DataStorage)result;
            
            LocationGroup lgr = new LocationGroup();
            //lgr.LOCATION_LAT=result.Provider.
            return lgr;
        }
        public List<LocationGroup> GetVariableListFromDataStorage(int siteId, int groupId)
        {
            throw new NotImplementedException();
        }
    }
}

ICOSCoreNew/Models/ViewModel/BADM/LocationGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ICOSCoreNew.Models.ViewModel.BADM
{
    public class LocationGroupViewModel
    {
        public string LOCATION_LAT { get; set; }
        public string LOCATION_LONG { get; set; }
        public string LOCATION_ELEV { get; set; }
        public string LOCATION_DATE { get; set; }
        public string LOCATION_COMMENT { get; set; }
        public string SITE { get; set; }  // TODO: AC - ok nel filtro o disturba o in una base class !!??? 
        public int SiteId { get; set; }
    }
}

ICOSCoreNew/Controllers/BADM/LocationGroupController.cs
using System.Threading.Tasks;
using ICOSCoreNew.Models.BADM;
using ICOSCoreNew.Models.DTO;
using ICOSCoreNew.Models.SqlDbServices;
using ICOSCoreNew.Models.ViewModel;
using ICOSCoreNew.Models.ViewModel.BADM;
using Microsoft.AspNetCore.Mvc;
using static ICOSCoreNew.Models.Utils.Globals;

namespace ICOSCoreNew.Controllers.BADM
{
    public class LocationGroupController : Controller
    {
        private IVariableAdapter<LocationGroup> adapter;
        private readonly IDataStorageServices iDataStorageService;

        public LocationGroupController(IVariableAdapter<LocationGroup> _adapter, IDataStorageServices _ids)
        {
            adapter = _adapter;
            iDataStorageService = _ids;
        }

        public async Task<IActionResult> Index()
        {
            //ICOSSitePiViewModel viewModel = new ICOSSitePiViewModel();
            //viewModel = await GetPISitesListAsync();
            ICOSSitePiViewModel viewModel = await iDataStorageService.GetPISitesViewModelListAsync();
            // return View(viewModel);
            return View("/Views/BADM/LocationGroup.cshtml", viewModel);
           // return View("BADM/Index");
        }

        [HttpPost]
        public JsonResult getData(LocationGroupViewModel location)
        {
            adapter.GetVariableFromDataStorage(location.SiteId, (int)BadmVarsGroups.GRP_LOCATION);
            return null;//base.getData<LocationGroupModel, LocationGroupAdapter, LocationGroupFilter, LocationGroupUI>(filter);
        }
    }
}

ICOSCoreNew/Controllers/BADM/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ICOSCoreNew.Controllers.BADM
{
    public class TeamController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ICOSCoreNew/Controllers/BADMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICOSCoreNew.DB;
using ICOSCoreNew.Models.SqlDbServices;
using ICOSCoreNew.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace ICOSCoreNew.Controllers
{
    public class BADMController : Controller
    {
        private readonly IDataStorageServices iDataStorageService;

        public BADMController(IDataStorageServices ids)
        {
            iDataStorageService = ids;
        }

        public async Task<IActionResult> Index()
        {
            if (AccountDA.CurrentUserID != 0)
            {
                if (AccountDA.CurrentICOS == 1)
                { 
                    //TODO
                    //return View(PiDA.GetTimelineEventsAndAlerts(70));
                    ICOSSitePiViewModel viewModel = await iDataStorageService.GetPISitesViewModelListAsync();
                    return View(viewModel);
                }
                else
                    return RedirectToAction("ChangePassword", "Account");
            }
            else
                return RedirectToAction("Login", "Account");
        }

        public IActionResult Team()
        {
            return View();
        }

        [HttpPost]
        public JsonResult getData()
        {
            return null; // Json(tmList);
        }
    }
}

ICOSCoreNew/Views/BADM/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model ICOSCoreNew.Models.ViewModel.ICOSSitePiViewModel
@{ 
    var x = Model;
}

<div class="col-md-12">
    <h1>BADM Online System</h1>
    <p>
        This online tool allow to check, correct and add ancillary data, metadata and all other information that are collected and stored using the BADM system. At the moment it is under development and allow the access to a limited number of variables that however will be increased continuously.
        Once you changed or added data remember to save the changes. For any question about the BADM system, the variables and the tool please don’t hesitate to contact us.
    </p>
    <partial name="_SiteSelectorPartial" model="Model" />
    <p>Please select one of following variable group to edit or insert data</p>
</div>
<partial name="_BADMMenuPartial" />

ICOSCoreNew/Views/BADM/LocationGroup.cshtml
@{
    ViewBag.Title = "BADM - Location Group";
    Layout = "~/Views/Shared/_LayoutICOS.cshtml";

}
<h1>BADM Online Tool</h1>
<partial name="_BADMMenuPartial" />

<h2 class="text-highlight">@(ViewBag.Title)</h2>
<div class="row">
    <div class="col-md-12">
        <div id="jsGrid"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <partial name="Dialog/_DialogStructurePartial" />
        @*Html.Partial("/Views/Shared/Dialog/_dialogStructure.cshtml")*@
        @*@Html.Partial("/Views/Shared/Dialog/_dialogInputLocationGroup.cshtml")*@
    </div>
</div>

<partial name="_SiteSelectorPartial" model="Model" />

@section scripts{
    <environment names="Development">
        <script src="~/js/jsgrid/jsgrid.js"></script>
        <script src="~/js/Custom/dialog.manager.js"></script>
        <script src="~/js/Custom/locationgroup.manager.js"></script>
        <link href="~/css/DataTables/media/css/jquery.dataTables.min.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="~/js/d3.min.js" asp-file-version="true"></script>
    </environment>
    <script type="text/javascript">
        var locationManager = new locationgroupMgr('#jsGrid', '#dlgStruct', '@Url.Action("Create", "LocationGroup")',
                                                    '@Url.Action("Update","LocationGroup")', '@Url.Action("Delete","LocationGroup")',
                                                    '@Url.Action("getData","LocationGroup")', '@Url.Action("GetdlgInputView","LocationGroup")');
        locationManager.Initialize();
    </script>
}

ICOSCoreNew/Views/BADM/Team.cshtml
@{
    ViewBag.Title = "BADM - Team ";
    ViewBag.GroupId = "12";
    Layout = "~/Views/Shared/_LayoutICOS.cshtml";
}

<h1>BADM Online Tool</h1>
<partial name="_BADMMenuPartial" />

<h2 class="text-highlight">@(ViewBag.Title)</h2>


<div class="row">
    <div class="col-md-12">
        <div id="jsGrid"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <partial name="Dialog/_DialogStructurePartial" />
    </div>
</div>

@section scripts{
<environment names="Development">
    <script src="~/js/jsgrid/jsgrid.js"></script>
    <script src="~/js/Custom/dialog.manager.js"></script>
    <script src="~/js/Custom/teammember.manager.js"></script>
    <link href="~/css/DataTables/media/css/jquery.dataTables.min.css" rel="stylesheet" />
</environment>
<environment names="Staging,Production">
    <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script src="~/js/d3.min.js" asp-file-version="true"></script>
</environment>
        @*Scripts.Render(

            "~/Scripts/moment.js",
            "~/Scripts/moment-with-locales.js",
            "~/Scripts/bootstrap-datetimepicker.js",

            "~/Scripts/Common/datepicker.js",


            "~/Scripts/Custom/person.jsgrid.rangenumber.js",
            "~/Scripts/jsgrid/jsgrid.js",
            "~/Scripts/Custom/dialog.manager.js",
            "~/Scripts/Custom/teammember.manager.js"
            )*@

        <script type="text/javascript">
        var teamManager = new teamMemberMgr('#jsGrid', '#dlgStruct', '@Url.Action("Create", "Team")', '@Url.Action("Update", "Team")', '@Url.Action("Delete", "Team")', '@Url.Action("getData", "BADM")', '@Url.Action("GetdlgInputTeam","Team")');
        teamManager.Initialize();
        </script>
    }