ICOSCoreNew/Models/Entities/Fieldbook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using ICOSCoreNew.Models.Entities;

namespace ICOSCoreNew.Models.Entities
{
    public class Fieldbook
    {
        [Key]
        public int id_fieldbook { get; set; }
        public string originalname { get; set; }
        public string data_info { get; set; }
        public int idins { get; set; }
        public int siteId { get; set; }
        public Nullable<int> data_type { get; set; }
        public string date { get; set; }
        public Nullable<DateTime> importDate { get; set; }
        public Nullable<DateTime> deletedDate { get; set; }
        public Nullable<short> status { get; set; }

        //public UserModel User { get; set; }
    }
}

ICOSCoreNew/Models/ViewModel/FieldBookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ICOSCoreNew.Models.ViewModel
{
    public class FieldBookViewModel
    {
        public string OriginalName { get; set; }
        public string DataInfo { get; set; }
        public string Content { get; set; }
        public Nullable<DateTime> ImportDate { get; set; }
        public string SubmitterName { get; set; }
    }
}

ICOSCoreNew/Models/ViewModel/SubmittedFilesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ICOSCoreNew.Models.ViewModel
{
    public class SubmittedFilesViewModel
    {
        public string Name { get; set; }
        public string OriginalName { get; set; }
        public string Submitter { get; set; }
        public string FileType { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Link { get; set; }
        public Nullable<DateTime> SumissionDate { get; set; }
    }
}

ICOSCoreNew/Controllers/PIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ICOSCoreNew.DB;
using System.IO;
using System.Reflection;
using ICOSCoreNew.Models;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;
using Microsoft.WindowsAzure.Storage.File;
using System.Text.RegularExpressions;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc;
using ICOSCoreNew.Models.UI;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using ICOSCoreNew.Models.Entities;
using ICOSCoreNew.Models.SqlDbServices;
using ICOSCoreNew.Models.ViewModel;
using System.Threading.Tasks;
using ICSharpCode.SharpZipLib.Zip;
using ICSharpCode.SharpZipLib.Core;
using Microsoft.Extensions.Configuration;
using ICOSCoreNew.Models.Utils;

namespace ICOSCoreNew.Controllers
{
    public class PIController : Controller
    {
        private readonly IDataStorageServices iDataStorageService;
        private readonly IConfiguration configuration;
       // private ICOS_site icos_site;

        public PIController(IDataStorageServices _ids, IConfiguration iConfig)
        {
            this.iDataStorageService = _ids;
            this.configuration = iConfig;
         //   icos_site = new ICOS_site();
        }
        public IActionResult Dashboard()
        {
            if ( AccountDA.CurrentUserID != 0)
            {
                if (AccountDA.CurrentICOS == 1)
                    //TODO
                    //return View(PiDA.GetTimelineEventsAndAlerts(70));
                return View();
                else
                    return RedirectToAction("ChangePassword", "Account");
            }
            else
                return RedirectToAction("Login", "Account");
        }

        public async Task<IActionResult> Fileupload()
        {
            ICOSSitePiViewModel viewModel = await iDataStorageService.GetPISitesViewModelListAsync();
            //viewModel = await GetPISitesListAsync();

            return View(viewModel);
        }

        /*public ActionResult TimeLineTest()
        {

            return View(PiDA.GetTimelineEventsAndAlerts(438));
        }

        public void SubmitTracknr(string eventId, string tracknr, string dateSent)
        {
            PiDA.SubmitTracknr(eventId, tracknr, dateSent);
        }
        public ActionResult Team()
        {
            return View();
        }
        public ActionResult Location()
        {
            return View();
        }

        public ActionResult Utc()
        {
            return View();
        }
        public ActionResult LandOwnership()
        {
            return View();
        }
        public ActionResult Tower()
        {
            return View();
        }
        public ActionResult Tree()
        {
            return View();
        }

        public ActionResult SPP()
        {
            return View();
        }

        public ActionResult Litter()
        {
            return View();
        }

        public ActionResult AGB()
        {
            return View();
        }
        public ActionResult BULK()
        {
            return View();
        }

        public ActionResult GAI()
        {
            return View();
        }

        public ActionResult CEPT()
        {
            return View();
        }
        public ActionResult ClimateAverage()
        {
            return View();
        }
        public ActionResult SamplingPlots()
        {
            return View();
        }
        public ActionResult FoliarSampling()
        {
            return View();
        }
        public ActionResult SoilSampling()
        {
            return View();
        }
        public ActionResult Dhp()
        {
            return View();
        }
        public ActionResult InstrumentalModel()
        {
            return View();
        }
        public ActionResult Logger()
        {
            return View();
        }
        public ActionResult FileModel()
        {
            return View();
        }
        public ActionResult EddyCovariance()
        {
            return View();
        }
        public ActionResult EcSystem()
        {
            return View();
        }
        public ActionResult MeteoMes()
        {
            return View();
        }
        public ActionResult StorageGroup()
        {
            return View();
        }
        public ViewResult Disturbance()
        {
            return View();
        }
        */
        
        
        
        /* */


        [HttpPost]
    public async Task<string> Save(List<IFormFile> files, string fileType, string site, string dataInfo, bool sampleCheck=false)
    {
        string message = "";
        string bodyMail = "A new $FF$ file has been submitted from the ICOS Upload web page\n"; ;
        string submittedFileType = "";
        //containing the files to attach to mail recipients
        List<string> filesToPost = new List<string>();
        //containing the mail recipients to send in CC
        List<string> lcc = new List<string>();
        if (!ModelState.IsValid)
        {
            return "An error occurred. Please contact administrators<br />info@icos-etc.eu";// RedirectToAction("Index");
        }
        else
        {
            //context = new ICOSEntities();
            int fType = int.Parse(fileType);
            int piSession = AccountDA.CurrentUserID;
            int siteID = 0; //iDataStorageService.GetSiteIdBySiteCode(site);//  context.ICOS_site.Where(sn => sn.site_code == site).Select(sn => sn.id_icos_site).SingleOrDefault();
            short? siteClass = 0; //context.ICOS_site.Where(sn => sn.id_icos_site == siteID).Select(sn => sn.@class).SingleOrDefault();
            iDataStorageService.GetSiteIdClassBySiteCode(site, ref siteID, ref siteClass);
            string newFileName = "";
            foreach (IFormFile file in files)
            {
                if (file != null)
                {

                        //ALL THE SAVEAS...ACTIONS FOR FILES I THINK NEED TO BE REWRITTEN IN ORDER TO save AS BLOB DATA TYPE....
                        //PROBLEM: SOME FILES NEED TO BE SENT TO RECIPIENTS IN ATTACHMENTS: SEE BELOW ON fType switch
                        //DIEGO:: end 
                        var path = Path.Combine(configuration.GetSection("DefaultUploadFolder").Value, file.FileName);

                    switch (fType)
                    {
                        case 12:
                                //BADM file: save to storage
                                //file.SaveAs(path);
                            newFileName = SetNewFileName(file.FileName);
                            message += "Processing " + file.FileName + "<br />";
                            submittedFileType = "BADM";
                            using (var stream = new FileStream(Path.Combine(configuration.GetSection("DefaultUploadFolder").Value, newFileName), FileMode.Create))
                            {
                                await file.CopyToAsync(stream);
                                message += "File succesfully uploaded<br />";
                            }
                                
                                break;
                        case 13:
                            //kml file: send attached to g.nicolini@unitus.it and create CP_SP file
                            if (sampleCheck)
                            {
                                    //check if CP points have been submitted
                                bool isCP = await iDataStorageService.CPRecordsExistAsync((int)Globals.BadmVarsGroups.GRP_PLOT, siteID, "CP_");
                                if (!isCP)
                                {
                                    return "WARNING! CP points coordinates are missing. Please submit by BADM Sampling Scheme Template or by the Web UI";
                                }

                                 //* create a txt file with ec-cp coordinates
                                 //fToJack = @"F:\icos\" + sitesList.SelectedItem.Text + "\\" + sitesList.SelectedItem.Text + "_EC-CP_coordinates.txt";
                                // getCooFile(sitesList.SelectedItem.Text, true, fToJack);

                                bodyMail += "\n\nSubmitter asked to treat the CPs as Exclusion Areas";
                            }

                            //file.SaveAs(path);
                           // string fToJack= Path.Combine(Server.MapPath("~/App_Data"), site + "_EC-CP_coordinates.txt");
                            string fToJack = Path.Combine(@"C:\Users\DiegoPolidori\source\repos\icoscore\ICOSCore\wwwroot\upload", site + "_EC -CP_coordinates.txt");
                            filesToPost.Add(fToJack);
                            lcc.Add("g.nicolini@unitus.it");
                            submittedFileType = "KML Target/Exclusion area";
                            break;
                        case 14:
                            //zip shape: send attached to g.nicolini@unitus.it and create CP_SP file
                            //file.SaveAs(path);
                            int shpFlag = 0;
                            submittedFileType = "zip Shape";
                            string taReg = @"^[a-zA-Z]{2}\-[a-zA-Z0-9]{3}_(TA).[a-zA-Z]{3}$";
                            string eaReg = @"[a-zA-Z]{2}\-[a-zA-Z0-9]{3}_(EA)([0][1-9]|[1][0-9]|20).[a-zA-Z]{3}$";
                            message += "Processing " + file.FileName  + "<br />";
                            string fExt = file.FileName.Substring(file.FileName.LastIndexOf(".") + 1);
                            string _fNameToChange = file.FileName.Substring(0, file.FileName.LastIndexOf("."));
                            ZipFile zf = new ZipFile(file.OpenReadStream());
                            string shp = _fNameToChange + ".shp";
                            string shx = _fNameToChange + ".shx";

ICOSCoreNew/Controllers/SiteSelectorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ICOSCoreNew.Models.Entities;
using ICOSCoreNew.Models.SqlDbServices;
using ICOSCoreNew.Models.UI;
using ICOSCoreNew.Models.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ICOSCoreNew.Controllers
{
    public class SiteSelectorController : Controller
    {
        private readonly IDataStorageServices iDataStorageService;
        private readonly ISitesListService iSitesListService;

        public SiteSelectorController(IDataStorageServices _ids, ISitesListService _iss)
        {
            this.iDataStorageService = _ids;
            this.iSitesListService = _iss;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> SiteSelect()
        {
            List<IcosSitePI> _tList = await iDataStorageService.GetPISitesListAsync();
            ICOSSitePiViewModel viewModel = new ICOSSitePiViewModel();
            viewModel.sitesPiList = new List<SelectListItem>();

            foreach(var _t in _tList)
            {
                viewModel.sitesPiList.Add(new SelectListItem(_t.site_code, _t.id_site.ToString()));
            }

            return View(viewModel);
        }
    }
}

ICOSCoreNew/Views/PI/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

<h1>Dashboard</h1>
<div class="row clearfix"></div>
<br />
<div class="col-md-12" style="margin-left:-10px">
    <p>
        This section is under construction and will be improved adding more and more tools for the PI and station staff. This will include a preview of the data received, news of interest for the station team, messages and deadlines for activities, links to the guidelines and all the ETC contact info.<br class="k-br" />
    </p>
    <p>
        The core tool available in this section is however the data submission service. This will be also improved in the next months with additional data types, more formal checks in order to ensure a correct data submission and more information. Some of the data are already being accepted, both in terms of files through the Upload Data service, and in terms of online editing and management of the BADM system information using the BADM Online Tool.<br />
        <br />
        It is also possible to upload BADM data by filling a relative template. Currently the final BADM are available to send data about the <strong>team description </strong>of the station team and the <strong>sampling scheme</strong>, which you can download from the links below.
    </p>
</div>
<div class="col-md-12" style="margin-left:-10px;">
    <h2 class="text-highlight">Actions</h2>
</div>
<div class="col-md-3" style="margin-left:-10px;">
    <a asp-controller="PI" asp-action="Fileupload" class="button rounded fill-highlight">Upload Data</a>
</div>
<!-- >div class="col-md-3" style="margin-left:-10px;">
    <a asp-controller="PI" asp-action="SiteSelector" class="button rounded fill-highlight">Site select</a>
</div -->
<div class="col-md-3">
    <a asp-controller="BADM" asp-action="Index" class="button rounded fill-highlight">BADM Online Tool</a>
</div>
<div class="col-md-3">
    <a asp-controller="PI" asp-action="Submittedfiles" class="button rounded fill-highlight">View Submitted Files</a>
</div>
<div class="col-md-3">
    <a asp-controller="PI" asp-action="Fieldbook" class="button rounded fill-highlight">Fieldbook</a>
</div>

ICOSCoreNew/Views/PI/Fieldbook.cshtml
@{
    ViewBag.Title = "Fieldbook";
    Layout = "~/Views/Shared/_LayoutICOS.cshtml";
}

@model ICOSCoreNew.Models.ViewModel.ICOSSitePiViewModel

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">

<style>
    #dataTable img {
        height: 120px;
        width: auto;
        border: 1px solid #cccccc;
    }

    .dataTables_length {
        display: none;
    }
</style>

<div class="col-md-12">
    <h1>Station Field book</h1>
    <p>The Field Book is a tool to help ICOS Station Teams to keep organized and safety stored the notes that are generally collected and reported when the site is visited. The idea is to move from a classical paper field book to a more organized and easily shared (inside the team) system that allows not only to report text but also photos, sketches and audio files.</p>
    <p>There are two ways to enter items in the Field Book: the tools here below and the ICOS ETC Upkeep APP. Both the systems end up on the same database so items entered with one are also visible in the other interface. The only difference is that items can be deleted only in the web version (here) and then will disappear also from the APP as soon as synchronized.</p>
</div>
<partial name="_SiteSelectorPartial" model="Model" />

@using (Html.BeginForm("", "", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="col-md-12" id="jsGrid">
        <hr />
        <h2 class="text-highlight">Field Book Items</h2>
        <table id="dataTable" class="display"></table>
        <hr />
    </div>

    <div class="col-md-12" id="additem">
        <h2 class="text-highlight">Add New Field Book Item</h2>
        <p>Select which type of item you want to add (text, image or audio). For images accepted formats are jpg and png. For audio file accepted formats are mp3 and 3gp (Android). Do not upload files larger than 10 Mb.</p>
        <select id="ddlType" name="ddlType">
            <option value="0">Please select</option>
            <option value="15">Text note</option>
            <option value="21">Audio file</option>
            <option value="22">Image file</option>
        </select>
    </div>
    <div class="col-md-12">
        <input type="text" id="textNote" name="textNote" required placeholder="Note title" /><br />
        <textarea id="note" name="note" maxlength="2000" rows="6" placeholder="Enter text"></textarea>
        <input type="file" id="files" name="files" /><br />
        <button id="buttonUpload" class="button rounded fill-highlight">Submit</button>
    </div>
}

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">File Upload report</h4>
            </div>
            <div class="modal-body">
                <p id="modal-text"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

@section Scripts {

<environment names="Development">
    <script src="~/js/jsgrid/jsgrid.js"></script>
    <script src="~/js/DataTables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/js/Custom/dialog.manager.js"></script>
    <link href="~/css/DataTables/media/css/jquery.dataTables.min.css" rel="stylesheet" />
</environment>
<environment names="Staging,Production">
    <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script src="~/js/d3.min.js" asp-file-version="true"></script>
</environment>

   
    <script type="text/javascript">
        var xch = "0";
        var choice = 0;
        var _selSite = "";
        var filesToUpload = [];
        var _idSite = $("#SiteId option:selected").val();

        $('#SiteId').on('change', function () {
            _idSite = this.value;
            console.log(_idSite);
            if (_idSite === "" || _idSite === undefined) {
                return;
            }
            $("#jsGrid").show();
            $("#additem").show();
            AjaxUpload(_idSite);
        });

        function AjaxUpload(sitePar) {
            $.ajax({
                /*xhr: function () {
                    var xhr = new window.XMLHttpRequest();
                    //Upload progress
                    xhr.upload.addEventListener("progress", function (evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = Math.round((evt.loaded / evt.total) * 100);
                            //Do something with upload progress
                            var loadingTxt = "";
                            if (percentComplete < 100) {
                                loadingTxt = "Loading... " + percentComplete;
                            }
                            else {
                                loadingTxt = "Please wait";
                            }
                            $("#modal-text").html(loadingTxt);

                            $("#myModal").modal('show');
                        }
                    }, false);

                    return xhr;
                },
                */
                dataType: 'json',
                url: "GetFieldbookData",
                type: "GET",
                data: { id: sitePar },
                success: function (result) {
                    var table = $("#dataTable").DataTable({
                        destroy: true,
                        data: result,
                        columns: [
                            //{ data: 'id_fieldbook', title: 'ID' },
                            { data: 'ImportDate', title: 'Date', width: '12%' },
                            { data: 'SubmitterName', title: 'Submitter Name' },
                            { data: 'DataInfo', title: 'Title', width: '20%' },
                            { data: 'Content', title: 'Content' }

                        ]
                    });

                },
                error: function (richiesta, stato, errori) {
                    console.log(errori);
                }
            });
        }

        $(document).ready(function () {
            $("#textNote").hide();
            $("#files").hide();
            $("#note").hide();
            $("#buttonUpload").hide();
            $("#jsGrid").hide();
            $("#additem").hide();
        });

        $('#ddlType').change(function (e) {
            choice = parseInt(e.target.value);
            if (choice == 0) {
                $("#files").hide();
                $("#textNote").hide();
                $("#buttonUpload").hide();
                return;
            }
            if (choice == 15) {
                $("#note").show();
                $("#files").hide();
                $("#buttonUpload").show();
            }
            if (choice == 21) {
                $("#note").hide();
                $("#files").show();
                $("#buttonUpload").hide();
            }
            if (choice == 22) {
                $("#note").hide();
                $("#files").show();
                $("#buttonUpload").hide();
            }
            $("#textNote").show();

        });

        $('#files').change(function (e) {
            if (e.target.files.length == 0) {
                return;
            }
            _selSite = $("#SiteId option:selected").text();
            var filename = e.target.files[0].name;

            var dot = filename.lastIndexOf(".");
            var ext = filename.substring(dot + 1).toLowerCase();
            var subFilenameSite = filename.substr(0, 6);
            var current_size = 0;
            var max_size = 10000000;
            /* if (subFilenameSite != _selSite) {
                 $("#modal-text").html("Warning! The site prefix of uploaded filename " + subFilenameSite + " does not match the selected site " + _selSite + "<br />");
                 $("#myModal").modal('show');
                 $(this).val(null);
                 return;
             }*/
            if (choice == 22) {
                if (ext.indexOf("jpg") < 0 && ext.indexOf("png") < 0) {
                    $("#modal-text").html("Warning! Only jpg or png format allowed");
                    $("#myModal").modal('show');
                    $(this).val(null);
                    return;
                }
                else {
                    var current_size = $("#files")[0].files[0].size;
                    if (current_size > max_size) {
                        $("#modal-text").html("Warning! File size exceeds max size allowed");
                        $("#myModal").modal('show');
                        $(this).val(null);
                        return;
                    }

                }
                $("#buttonUpload").show();
            }
            if (choice == 21) {
                if (ext.indexOf("mp3") < 0 && ext.indexOf("3gp") < 0) {
                    $("#modal-text").html("Warning! Only mp3 or 3gp format allowed");
                    $("#myModal").modal('show');
                    $(this).val(null);
                    return;
                }
                else
                    var current_size = $("#files")[0].files[0].size;
                if (current_size > max_size) {
                    $("#modal-text").html("Warning! File size exceeds max size allowed");
                    $("#myModal").modal('show');
                    $(this).val(null);
                    return;
                }
                $("#buttonUpload").show();
            }
            filesToUpload.push({
                file: e.target.files[0]
            });
        });

        $("#buttonUpload").click(function (e) {
            e.preventDefault();
            if ($.trim($("#textNote").val()).length == 0) {
                $("#modal-text").html("Warning! Please enter a note title");
                $("#myModal").modal('show');
                return;
            }
            var note_info = $("#note").val();
            let fData = new FormData();
            for (i = 0; i < filesToUpload.length; i++) {
                fData.append('files', filesToUpload[i].file, filesToUpload[i].name);
            }
            fData.append('fileType', $("#ddlType option:selected").val());
            fData.append('data_info', $("#textNote").val());
            fData.append('site', $("#SiteId option:selected").text());
            fData.append('note_info', note_info);

            //return;
            $.ajax({
                xhr: function () {
                    var xhr = new window.XMLHttpRequest();
                    //Upload progress
                    xhr.upload.addEventListener("progress", function (evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = Math.round((evt.loaded / evt.total) * 100);
                            //Do something with upload progress
                            var loadingTxt = "";
                            if (percentComplete < 100) {
                                loadingTxt = "Loading... " + percentComplete;
                            }
                            else {
                                loadingTxt = "Please wait";

                            }
                            $("#modal-text").html(loadingTxt);

                            $("#myModal").modal('show');
                        }
                    }, false);

                    return xhr;
                },

                url: '/pi/fbook/',
                type: 'POST',
                cache: false,
                contentType: false,
                processData: false,
                data: fData,
                success: function (data) {
                    $("#files").val(null);
                    $("#modal-text").html(data);
                    $("#myModal").modal('show');
                    $("#textNote").val("");
                    $("#note").val("");
                    $('#ddlType').val(0);
                    filesToUpload = [];
                    AjaxUpload(_idSite);
                },
                error: function (data) {
                    $("#modal-text").html("Error in uploading Fieldbook data. Please contact administration (info@icos-etc.eu)");
                    $("#files").val(null);
                    filesToUpload = [];
                }


            });
        });
    </script>
}

ICOSCoreNew/Views/PI/_SiteSelector.cshtml
@model ICOSCore.Models.UI.SelectorVM


<h2>Site Selector</h2>
<div class="row">
    <div class="col-md-12">
        <span>Select your site:</span>
        <select asp-for="@Model" asp-items="@Model.SiteList">
            <option value="">Please select...</option>
        </select>
    </div>
</div>

ICOSCoreNew/Views/PI/__SiteSelector.cshtml
@{
    Layout = null;
    SelectList allsites = ViewBag.sitemenu;
}
@model ICOSCore.Models.UI.SelectorVM

<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        $("#Id_site").change(function () {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("SetSite", "Pi")' + '?siteId=' + this.value,
                data: {},
                success: function (result) {
                   // alert(result);
                    //refreshGrid();
                    location.reload();
                },
                error: function () { alert('Error'); }
            });
        });
    });
</script>
<style>
    .siteselectorlabel
    { display:inline;}
</style>

<div class="row">
    <div class="col-md-12">
        <span>Select your site:</span>
        @*@Html.LabelFor(m => m.SiteList, new { @class="siteselectorlabel"})*@
        @*@Html.DropDownList("xpisitesmenu", Model.SiteList)*@
        <select asp-for="@Model.Id_site" >
            <option value="">Please select...</option>
            <options asp-items="@Model.SiteList" />
        </select>
        @*Html.DropDownListFor(m => m.Id_site, Model.SiteList)*@
    </div>
</div>